repos:
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.1
    hooks:
    - id: isort
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
